import { useEffect, useMemo, useState } from 'react'
import { Button, Card, CardBody, Chip, Input, Spinner } from '@heroui/react'
import { AlertTriangle, Boxes, ChevronRight, CircleHelp, ClipboardList, LayoutDashboard, LogOut, Menu, Package, Search, Settings, Truck, UserPlus, X } from 'lucide-react'
import { api, Category, InventoryItem, Product, User, Warehouse } from './api'

type View = 'overview' | 'inventory' | 'products' | 'categories' | 'warehouses'
const nav = [{ id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'inventory', label: 'Inventory', icon: Boxes }, { id: 'products', label: 'Products', icon: Package }, { id: 'categories', label: 'Categories', icon: ClipboardList }, { id: 'warehouses', label: 'Warehouses', icon: Truck }] as const

function Login({ onAuth }: { onAuth: (user: User) => void }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ username: '', email: '', password: '', role: 'Staff' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { const user = register ? await api.register(form) : await api.login({ email: form.email, password: form.password }); localStorage.setItem('flowline_token', user.token); localStorage.setItem('flowline_user', JSON.stringify(user)); onAuth(user) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in') } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-art"><div className="brand"><span className="brand-mark"><Boxes size={22} /></span><span>flowline</span></div><div className="auth-copy"><p className="eyebrow">SUPPLY CHAIN OPERATIONS</p><h1>Move every<br /><em>part</em> forward.</h1><p className="muted-on-dark">A clearer view of your network, from dock to doorstep.</p></div><div className="network-lines" /></section><section className="auth-panel"><div className="auth-form-wrap"><div className="mobile-brand brand"><span className="brand-mark"><Boxes size={22} /></span><span>flowline</span></div><p className="eyebrow">WELCOME BACK</p><h2>{register ? 'Create your workspace' : 'Good to see you.'}</h2><p className="auth-sub">{register ? 'Set up your operations account.' : 'Sign in to your operations workspace.'}</p><form onSubmit={submit} className="stack">{register && <Input label="Your name" placeholder="Alex Morgan" value={form.username} onValueChange={v => setForm({ ...form, username: v })} isRequired /> }<Input label="Work email" type="email" placeholder="you@company.com" value={form.email} onValueChange={v => setForm({ ...form, email: v })} isRequired /><Input label="Password" type="password" placeholder="At least 12 characters" value={form.password} onValueChange={v => setForm({ ...form, password: v })} isRequired />{register && <label className="select-label">Role<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}><option>Staff</option><option>Warehouse Manager</option><option>Admin</option></select></label>}{error && <div className="error-box"><AlertTriangle size={16} />{error}</div>}<Button type="submit" className="primary-btn" isDisabled={busy}>{busy ? <Spinner size="sm" color="white" /> : register ? 'Create account' : 'Sign in'}<ChevronRight size={17} /></Button></form><p className="switch-auth">{register ? 'Already have an account?' : "Don't have an account?"} <button onClick={() => { setRegister(!register); setError('') }}>{register ? 'Sign in' : 'Create one'}</button></p></div></section></main>
}

function App() {
  const [user, setUser] = useState<User | null>(() => { try { return JSON.parse(localStorage.getItem('flowline_user') || 'null') } catch { return null } })
  return user ? <Dashboard user={user} onLogout={() => { localStorage.clear(); setUser(null) }} /> : <Login onAuth={setUser} />
}

function Dashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [view, setView] = useState<View>('overview'); const [mobileNav, setMobileNav] = useState(false); const [inventory, setInventory] = useState<InventoryItem[]>([]); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [loading, setLoading] = useState(true); const [lowOnly, setLowOnly] = useState(false); const [query, setQuery] = useState(''); const [toast, setToast] = useState('')
  const load = async () => { setLoading(true); try { const [i, p, c, w] = await Promise.all([api.inventory(lowOnly), api.products(), api.categories(), api.warehouses()]); setInventory(i); setProducts(p); setCategories(c); setWarehouses(w) } catch (e) { setToast(e instanceof Error ? e.message : 'Could not load data') } finally { setLoading(false) } }
  useEffect(() => { load() }, [lowOnly])
  const shownInventory = useMemo(() => inventory.filter(i => `${i.productName} ${i.warehouseName}`.toLowerCase().includes(query.toLowerCase())), [inventory, query])
  const lowCount = inventory.filter(i => i.isLowStock).length
  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="side-brand brand"><span className="brand-mark"><Boxes size={21} /></span><span>flowline</span><button className="close-nav" onClick={() => setMobileNav(false)}><X size={19} /></button></div><p className="side-label">WORKSPACE</p><nav>{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => { setView(item.id); setMobileNav(false) }}><Icon size={18} />{item.label}{item.id === 'inventory' && lowCount > 0 && <span className="nav-badge">{lowCount}</span>}</button> })}</nav><div className="side-bottom"><button className="nav-item"><Settings size={18} />Settings</button><button className="nav-item"><CircleHelp size={18} />Support</button><div className="user-card"><div className="avatar">{user.username.slice(0, 1).toUpperCase()}</div><div><strong>{user.username}</strong><span>{user.role}</span></div><button onClick={onLogout} aria-label="Sign out"><LogOut size={17} /></button></div></div></aside><div className="content-shell"><header className="topbar"><button className="menu-btn" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div className="crumb"><span>Workspace</span><ChevronRight size={14} /><b>{nav.find(n => n.id === view)?.label}</b></div><div className="top-actions"><div className="top-search"><Search size={16} /><input placeholder="Search anything..." value={query} onChange={e => setQuery(e.target.value)} /></div><div className="avatar small">{user.username.slice(0, 1).toUpperCase()}</div></div></header><main className="main-content">{toast && <div className="toast error-box"><AlertTriangle size={16} />{toast}<button onClick={() => setToast('')}><X size={15} /></button></div>}{view === 'overview' && <Overview inventory={inventory} products={products} warehouses={warehouses} lowCount={lowCount} onInventory={() => setView('inventory')} />}{view === 'inventory' && <InventoryView items={shownInventory} lowOnly={lowOnly} setLowOnly={setLowOnly} loading={loading} />}{view === 'products' && <EntityView title="Products" subtitle="Your complete product catalog." rows={products.map(p => [p.name, p.sku, `$${p.price.toLocaleString()}`, categories.find(c => c.id === p.categoryId)?.name || 'Uncategorised'])} headers={['Product', 'SKU', 'Unit price', 'Category']} empty="No products found." />}{view === 'categories' && <EntityView title="Categories" subtitle="Organise products into meaningful groups." rows={categories.map(c => [c.name, c.description || '—'])} headers={['Category', 'Description']} empty="No categories found." />}{view === 'warehouses' && <EntityView title="Warehouses" subtitle="Locations across your distribution network." rows={warehouses.map(w => [w.name, w.location])} headers={['Warehouse', 'Location']} empty="No warehouses found." />}</main></div></div>
}

function Overview({ inventory, products, warehouses, lowCount, onInventory }: { inventory: InventoryItem[]; products: Product[]; warehouses: Warehouse[]; lowCount: number; onInventory: () => void }) {
  const units = inventory.reduce((n, i) => n + i.quantity, 0); return <><div className="page-heading"><div><p className="eyebrow">TUESDAY, SEPTEMBER 16, 2026</p><h1>Good morning.</h1><p className="subheading">Here’s what’s happening across your network today.</p></div><Button className="outline-btn" onClick={onInventory}><ClipboardList size={16} />View inventory</Button></div><div className="metric-grid"><Metric label="Total units" value={units.toLocaleString()} trend="+12.8%" icon={Boxes} /><Metric label="Products" value={products.length.toString()} trend="+4.2%" icon={Package} /><Metric label="Warehouses" value={warehouses.length.toString()} trend="All active" icon={Truck} /><Metric label="Low stock" value={lowCount.toString()} trend={lowCount ? 'Needs attention' : 'All clear'} icon={AlertTriangle} warning={lowCount > 0} /></div><div className="dashboard-grid"><Card className="panel"><CardBody><div className="panel-head"><div><h3>Inventory health</h3><p>Stock levels across all locations</p></div><span className="status-dot"><i />Live</span></div><div className="health-bar"><span style={{ width: `${Math.max(8, ((inventory.length - lowCount) / Math.max(inventory.length, 1)) * 100)}%` }} /></div><div className="health-legend"><span><i className="good" />Healthy <b>{inventory.length - lowCount}</b></span><span><i className="warn" />Low stock <b>{lowCount}</b></span></div></CardBody></Card><Card className="panel"><CardBody><div className="panel-head"><div><h3>Attention needed</h3><p>Items below their threshold</p></div><button className="text-btn" onClick={onInventory}>See all <ChevronRight size={15} /></button></div>{inventory.filter(i => i.isLowStock).slice(0, 3).map(i => <div className="attention-row" key={i.id}><div className="product-icon"><Package size={16} /></div><div><strong>{i.productName}</strong><span>{i.warehouseName}</span></div><Chip size="sm" className="low-chip">{i.quantity} left</Chip></div>)}{!lowCount && <p className="empty-copy">Everything is stocked up for now.</p>}</CardBody></Card></div></>
}
function Metric({ label, value, trend, icon: Icon, warning }: { label: string; value: string; trend: string; icon: typeof Boxes; warning?: boolean }) { return <Card className="metric"><CardBody><div className={`metric-icon ${warning ? 'warning' : ''}`}><Icon size={19} /></div><p>{label}</p><strong>{value}</strong><span className={warning ? 'metric-trend warning-text' : 'metric-trend'}>{trend}</span></CardBody></Card> }
function InventoryView({ items, lowOnly, setLowOnly, loading }: { items: InventoryItem[]; lowOnly: boolean; setLowOnly: (v: boolean) => void; loading: boolean }) { return <><div className="page-heading compact"><div><p className="eyebrow">OPERATIONS</p><h1>Inventory</h1><p className="subheading">Track stock levels and replenishment needs.</p></div><Button className={lowOnly ? 'filter-btn selected' : 'filter-btn'} onClick={() => setLowOnly(!lowOnly)}><AlertTriangle size={16} />Low stock only</Button></div><Card className="table-card"><CardBody><div className="table-toolbar"><div><h3>Stock overview</h3><p>{items.length} inventory records</p></div><button className="refresh-btn" onClick={() => location.reload()}>Refresh</button></div>{loading ? <div className="loading"><Spinner color="primary" /></div> : <div className="table-wrap"><table><thead><tr><th>Product</th><th>Warehouse</th><th>Quantity</th><th>Threshold</th><th>Status</th><th>Last updated</th></tr></thead><tbody>{items.map(i => <tr key={i.id}><td><strong>{i.productName}</strong><span className="cell-muted">#{i.productId.toString().padStart(4, '0')}</span></td><td>{i.warehouseName}</td><td><b className={i.isLowStock ? 'quantity-low' : ''}>{i.quantity}</b> units</td><td>{i.lowStockThreshold}</td><td><span className={i.isLowStock ? 'status-pill low' : 'status-pill healthy'}><i />{i.isLowStock ? 'Low stock' : 'Healthy'}</span></td><td>{new Date(i.lastUpdated).toLocaleDateString()}</td></tr>)}</tbody></table>{!items.length && <p className="empty-copy">No inventory matches this view.</p>}</div>}</CardBody></Card></> }
function EntityView({ title, subtitle, rows, headers, empty }: { title: string; subtitle: string; rows: string[][]; headers: string[]; empty: string }) { return <><div className="page-heading compact"><div><p className="eyebrow">CATALOG</p><h1>{title}</h1><p className="subheading">{subtitle}</p></div><Button className="outline-btn"><UserPlus size={16} />Add {title.slice(0, -1).toLowerCase()}</Button></div><Card className="table-card"><CardBody><div className="table-toolbar"><div><h3>All {title.toLowerCase()}</h3><p>{rows.length} records</p></div></div><div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className={j === 0 ? 'strong-cell' : ''}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="empty-copy">{empty}</p>}</div></CardBody></Card></> }
export default App
