import { useEffect, useState } from 'react'
import { Button, Card, CardBody, Input, Spinner } from '@heroui/react'
import { ClipboardCheck, PackagePlus, Truck, UserPlus } from 'lucide-react'
import { api, Product, Supplier, Warehouse } from './api'

type Props = { products: Product[]; warehouses: Warehouse[]; onChanged: () => void }
type Notice = { text: string; error?: boolean }

export function OperationsPanel({ products, warehouses, onChanged }: Props) {
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [notice, setNotice] = useState<Notice | null>(null)
  const [busy, setBusy] = useState(false)
  const [supplier, setSupplier] = useState({ name: '', contactEmail: '', phone: '' })
  const [stock, setStock] = useState({ productId: '', warehouseId: '', quantity: '', lowStockThreshold: '10', reason: 'Manual adjustment' })
  const [purchase, setPurchase] = useState({ supplierId: '', productId: '', quantity: '1', unitPrice: '0', warehouseId: '' })
  const [fulfillment, setFulfillment] = useState({ customerName: '', shippingAddress: '', productId: '', quantity: '1', warehouseId: '' })

  const loadSuppliers = async () => setSuppliers(await api.suppliers())
  useEffect(() => { loadSuppliers().catch(() => undefined) }, [])
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setNotice(null); try { await action(); setNotice({ text: success }); onChanged(); await loadSuppliers() } catch (e) { setNotice({ text: e instanceof Error ? e.message : 'Operation failed', error: true }) } finally { setBusy(false) } }
  const selectedProduct = products[0]?.id ?? 0
  const selectedWarehouse = warehouses[0]?.id ?? 0
  return <><div className="page-heading compact"><div><p className="eyebrow">OPERATIONS</p><h1>Supply chain actions</h1><p className="subheading">Manage suppliers, stock, inbound purchasing, and outgoing fulfillment.</p></div></div>{notice && <div className={notice.error ? 'error-box' : 'success-box'}>{notice.text}</div>}<div className="operation-grid">
    <Card className="table-card"><CardBody><div className="operation-title"><UserPlus size={18} /><h3>New supplier</h3></div><form className="stack" onSubmit={e => { e.preventDefault(); return run(() => api.createSupplier(supplier), 'Supplier created.') }}><Input label="Supplier name" value={supplier.name} onValueChange={v => setSupplier({ ...supplier, name: v })} isRequired /><Input label="Contact email" type="email" value={supplier.contactEmail} onValueChange={v => setSupplier({ ...supplier, contactEmail: v })} isRequired /><Input label="Phone" value={supplier.phone} onValueChange={v => setSupplier({ ...supplier, phone: v })} /><Button type="submit" className="outline-btn" isDisabled={busy}><UserPlus size={15} />Save supplier</Button></form><div className="mini-list">{suppliers.map(s => <div key={s.id}><strong>{s.name}</strong><span>{s.contactEmail}</span></div>)}</div></CardBody></Card>
    <Card className="table-card"><CardBody><div className="operation-title"><ClipboardCheck size={18} /><h3>Adjust inventory</h3></div><form className="stack" onSubmit={e => { e.preventDefault(); return run(() => api.adjustInventory({ productId: Number(stock.productId || selectedProduct), warehouseId: Number(stock.warehouseId || selectedWarehouse), quantity: Number(stock.quantity), lowStockThreshold: Number(stock.lowStockThreshold), reason: stock.reason }), 'Inventory adjusted and audit logged.') }}><select value={stock.productId} onChange={e => setStock({ ...stock, productId: e.target.value })}><option value="">Select product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={stock.warehouseId} onChange={e => setStock({ ...stock, warehouseId: e.target.value })}><option value="">Select warehouse</option>{warehouses.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select><Input label="Quantity change (+/-)" type="number" value={stock.quantity} onValueChange={v => setStock({ ...stock, quantity: v })} isRequired /><Input label="Low-stock threshold" type="number" value={stock.lowStockThreshold} onValueChange={v => setStock({ ...stock, lowStockThreshold: v })} /><Input label="Reason" value={stock.reason} onValueChange={v => setStock({ ...stock, reason: v })} isRequired /><Button type="submit" className="outline-btn" isDisabled={busy}><ClipboardCheck size={15} />Apply adjustment</Button></form></CardBody></Card>
    <Card className="table-card"><CardBody><div className="operation-title"><PackagePlus size={18} /><h3>Create purchase order</h3></div><form className="stack" onSubmit={e => { e.preventDefault(); return run(() => api.createPurchaseOrder({ supplierId: Number(purchase.supplierId), items: [{ productId: Number(purchase.productId || selectedProduct), quantity: Number(purchase.quantity), unitPrice: Number(purchase.unitPrice) }] }), 'Purchase order created.') }}><select value={purchase.supplierId} onChange={e => setPurchase({ ...purchase, supplierId: e.target.value })}><option value="">Select supplier</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={purchase.productId} onChange={e => setPurchase({ ...purchase, productId: e.target.value })}><option value="">Select product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><Input label="Quantity" type="number" value={purchase.quantity} onValueChange={v => setPurchase({ ...purchase, quantity: v })} /><Input label="Unit price" type="number" value={purchase.unitPrice} onValueChange={v => setPurchase({ ...purchase, unitPrice: v })} /><Button type="submit" className="outline-btn" isDisabled={busy || !purchase.supplierId}><PackagePlus size={15} />Create PO</Button></form></CardBody></Card>
    <Card className="table-card"><CardBody><div className="operation-title"><Truck size={18} /><h3>Fulfill customer order</h3></div><form className="stack" onSubmit={e => { e.preventDefault(); return run(() => api.createFulfillment({ customerName: fulfillment.customerName, shippingAddress: fulfillment.shippingAddress, items: [{ productId: Number(fulfillment.productId || selectedProduct), quantity: Number(fulfillment.quantity), warehouseId: Number(fulfillment.warehouseId || selectedWarehouse) }] }), 'Fulfillment order created and stock deducted.') }}><Input label="Customer name" value={fulfillment.customerName} onValueChange={v => setFulfillment({ ...fulfillment, customerName: v })} isRequired /><Input label="Shipping address" value={fulfillment.shippingAddress} onValueChange={v => setFulfillment({ ...fulfillment, shippingAddress: v })} isRequired /><select value={fulfillment.productId} onChange={e => setFulfillment({ ...fulfillment, productId: e.target.value })}><option value="">Select product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={fulfillment.warehouseId} onChange={e => setFulfillment({ ...fulfillment, warehouseId: e.target.value })}><option value="">Select warehouse</option>{warehouses.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select><Input label="Quantity" type="number" value={fulfillment.quantity} onValueChange={v => setFulfillment({ ...fulfillment, quantity: v })} /><Button type="submit" className="outline-btn" isDisabled={busy}><Truck size={15} />Fulfill order</Button></form></CardBody></Card>
  </div>{busy && <div className="loading"><Spinner color="primary" /></div>}</>
}
